LIST characters=alex,beatrice,charlie
VAR currentSpeaker = ""
VAR shop_state = "closed"
LIST Alex = (alex_normal)
LIST Beatrice = (beatrice_normal)
LIST Charlie = (charlie_normal)
VAR day = 0
VAR task = ""
VAR end_of_day = "false"
VAR gift = ""
VAR tutorialpt1 = "complete"
VAR tutorialpt2 = "complete"
VAR tutorialpt3 = "complete"
VAR tutorialCounter = 2